# Generated by Django 3.1 on 2020-08-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200830_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cn_name', models.CharField(max_length=20, null=True)),
                ('cn_email', models.EmailField(max_length=30, null=True)),
                ('cn_description', models.TextField(null=True)),
            ],
        ),
    ]
